### PR TITLE
Migrated to Grails 3

### PR DESCRIPTION
**Pull request by puneetbehl**

### CODE REVIEW

**Comment by puneetbehl** [comment]
@stefanogualdi  It seems like you merged some new changes into master. I can work on rebasing on top of current master. But, I have few questions:
- plugin name and version in static resource urls was not working so I have removed plugin from all `g.resource(dir: '<some-dir>', plugin: 'ckeditor')` tags.
- In Grails 3, all static resources are served as `/static/<path-to-resource>` so for this I have added default config in plugin.groovy 
```
grails.resources.pattern = '/**'
grails.resources.uri.prefix = ''
```

Please let me know if you see any concerns or issues.

**Comment by stefanogualdi** [comment]
I Puneet, first of all tank you for your contribution.

I've just merged a PR from another user. The only modification was on PluginUtils.groovy.

Feel free to change whatever you want

**Comment by puneetbehl** [comment]
Done, resolved conflicts :-)

**Comment by stefanogualdi** [comment]
thank you :)

**Comment by stefanogualdi** [comment]
Merged on master, thank you!

**Comment by puneetbehl** [comment]
@stefanogualdi  Do you want me to release over binary as well?

**Comment by stefanogualdi** [comment]
I’m just doing this! :)


On 28 March 2016 at 10:27:23, Puneet Behl (notifications@github.com) wrote:

@stefanogualdi Do you want me to release over binary as well?

**Comment by puneetbehl** [comment]
Cool :-) One more thing I noticed that one commit [98f1bf0: cleanup ](https://github.com/stefanogualdi/grails-ckeditor/pull/23/commits/98f1bf056379dca7345f9f8af870aaff849823bd) is missing in merge.

**Comment by stefanogualdi** [comment]
yes, I didn't notice the commit because I was manually merging. anyway I
deleted the files in my branch.

sent from mobile

**Pull request closed without merging**
